defmodule UnlokaoWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :unlokao

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_unlokao_key",
    signing_salt: "tSdHa7At",
    same_site: "Lax"
  ]

  # socket "/live", Phoenix.LiveView.Socket,
  #   websocket: [connect_info: [session: @session_options]],
  #   longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :unlokao,
    gzip: not code_reloading?,
    only: UnlokaoWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :unlokao
  end

  # Atrás do proxy da hospedagem, o IP do cliente vem no X-Forwarded-For.
  # Sem isso o limite de tentativas contaria todos os usuários como um IP só.
  plug RemoteIp

  plug Plug.RequestId

  # CORS: libera o front (outra origem) a chamar a API. As origens vêm de
  # `config :unlokao, :cors_origens` (em prod, da variável CORS_ORIGINS).
  # Sem cookies: a autenticação é por token no cabeçalho Authorization.
  plug CORSPlug,
    origin: &__MODULE__.cors_origens/0,
    credentials: false,
    headers: ["Authorization", "Content-Type", "Accept"],
    expose: ["Location", "Retry-After"]

  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug UnlokaoWeb.Router

  @doc false
  def cors_origens, do: Application.fetch_env!(:unlokao, :cors_origens)
end
